// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqF4GA3SjG6--0SiMfGYyrxK2nJwVS2BI',
    appId: '1:544272846899:web:8a011f5e56f7836927d346',
    messagingSenderId: '544272846899',
    projectId: 'moody-e9fdc',
    authDomain: 'moody-e9fdc.firebaseapp.com',
    storageBucket: 'moody-e9fdc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4pr1ESt-qqe5Yig0zYOMKPF2LePeyJcA',
    appId: '1:544272846899:android:088b8e89b1ae064027d346',
    messagingSenderId: '544272846899',
    projectId: 'moody-e9fdc',
    storageBucket: 'moody-e9fdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkXEhxMj0BC6vLtOC3wlCOErhdAyr37DE',
    appId: '1:544272846899:ios:98f073033e61b6c127d346',
    messagingSenderId: '544272846899',
    projectId: 'moody-e9fdc',
    storageBucket: 'moody-e9fdc.appspot.com',
    iosClientId:
        '544272846899-bsqtungso5ojr4d21cdesjf8q7oskrjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.moody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkXEhxMj0BC6vLtOC3wlCOErhdAyr37DE',
    appId: '1:544272846899:ios:98f073033e61b6c127d346',
    messagingSenderId: '544272846899',
    projectId: 'moody-e9fdc',
    storageBucket: 'moody-e9fdc.appspot.com',
    iosClientId:
        '544272846899-bsqtungso5ojr4d21cdesjf8q7oskrjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.moody',
  );
}
